=== anti-mony/MavEval/API_Python/api/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "examples": [
    {
      "name": "Butter Cookies",
      "description": "Quick and easy way to bake delicious butter cookies",
      "type": "Non Vegetarian (includes egg)",
      "category": "Snack",
      "preptime": 20,
      "servings": 12,
      "calories": 125,
      "instructions": "Preheat oven to 150 degree celcius. Mix Batter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed urna porttitor, aliquam lectus quis, vulputate elit. Fusce id vulputate sapien, a ultricies nulla. Sed leo justo, faucibus ac mi vel, scelerisque gravida neque. Mauris dignissim luctus enim a convallis. Etiam porttitor ex non lacus gravida, vitae pretium ipsum malesuada. In pellentesque, tellus porttitor imperdiet suscipit, magna arcu lacinia dolor, sit amet imperdiet felis eros tincidunt erat. Vestibulum egestas risus non ornare aliquet. Nullam lobortis cursus ultricies",
      "ingredients": [
        {
          "name": "Butter",
          "quantity": 50,
          "unit": "grams"
        },
        {
          "name": "Mix",
          "quantity": 1,
          "unit": "box"
        },
        {
          "name": "egg",
          "quantity": 1,
          "unit": ""
        }
      ]
    }
  ],
  "required": [
    "name",
    "description",
    "type",
    "category",
    "preptime",
    "servings",
    "calories",
    "instructions",
    "ingredients"
  ],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The name schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["Butter Cookies"]
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "The description schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["Quick and easy way to bake delicious butter cookies"]
    },
    "type": {
      "$id": "#/properties/type",
      "type": "string",
      "title": "The type schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["Non Vegetarian (includes egg)"]
    },
    "category": {
      "$id": "#/properties/category",
      "type": "string",
      "title": "The category schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["Snack"]
    },
    "preptime": {
      "$id": "#/properties/preptime",
      "type": "integer",
      "title": "The preptime schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [20]
    },
    "servings": {
      "$id": "#/properties/servings",
      "type": "integer",
      "title": "The servings schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [12]
    },
    "calories": {
      "$id": "#/properties/calories",
      "type": "integer",
      "title": "The calories schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [125]
    },
    "instructions": {
      "$id": "#/properties/instructions",
      "type": "string",
      "title": "The instructions schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Preheat oven to 150 degree celcius. Mix Batter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed urna porttitor, aliquam lectus quis, vulputate elit. Fusce id vulputate sapien, a ultricies nulla. Sed leo justo, faucibus ac mi vel, scelerisque gravida neque. Mauris dignissim luctus enim a convallis. Etiam porttitor ex non lacus gravida, vitae pretium ipsum malesuada. In pellentesque, tellus porttitor imperdiet suscipit, magna arcu lacinia dolor, sit amet imperdiet felis eros tincidunt erat. Vestibulum egestas risus non ornare aliquet. Nullam lobortis cursus ultricies"
      ]
    },
    "ingredients": {
      "$id": "#/properties/ingredients",
      "type": "array",
      "title": "The ingredients schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "name": "Butter",
            "quantity": 50,
            "unit": "grams"
          },
          {
            "name": "Mix",
            "quantity": 1,
            "unit": "box"
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/ingredients/items",
        "anyOf": [
          {
            "$id": "#/properties/ingredients/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "name": "Butter",
                "quantity": 50,
                "unit": "grams"
              }
            ],
            "required": ["name", "quantity", "unit"],
            "properties": {
              "name": {
                "$id": "#/properties/ingredients/items/anyOf/0/properties/name",
                "type": "string",
                "title": "The name schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["Butter"]
              },
              "quantity": {
                "$id": "#/properties/ingredients/items/anyOf/0/properties/quantity",
                "type": "integer",
                "title": "The quantity schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [50]
              },
              "unit": {
                "$id": "#/properties/ingredients/items/anyOf/0/properties/unit",
                "type": "string",
                "title": "The unit schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["grams"]
              }
            },
            "additionalProperties": true
          }
        ]
      }
    }
  },
  "additionalProperties": true
}

=== anti-mony/MavEval/API_Python/tests/recipie.json
{
  "name": "Nice Food",
  "description": "Quick and easy way to bake delicious butter cookies",
  "type": "Vegetarian",
  "category": "Snack",
  "preptime": 20,
  "servings": 10,
  "calories": 100,
  "instructions": "Preheat oven to 150 degree celcius. Mix Batter. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed urna porttitor, aliquam lectus quis, vulputate elit. Fusce id vulputate sapien, a ultricies nulla. Sed leo justo, faucibus ac mi vel, scelerisque gravida neque. Mauris dignissim luctus enim a convallis. Etiam porttitor ex non lacus gravida, vitae pretium ipsum malesuada. In pellentesque, tellus porttitor imperdiet suscipit, magna arcu lacinia dolor, sit amet imperdiet felis eros tincidunt erat. Vestibulum egestas risus non ornare aliquet. Nullam lobortis cursus ultricies",
  "ingredients": [
    {
      "name": "Butter",
      "quantity": 50,
      "unit": "grams"
    },
    {
      "name": "Egg",
      "quantity": 1,
      "unit": ""
    }
  ]
}
